<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://SOA.ATMproject.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://www.example.org/WebServiceATM/" name="ATMwsImplService" targetNamespace="http://SOA.ATMproject.com/">
  <wsdl:import location="http://localhost:8080/ATMservice/ATMservice?wsdl=WebServiceATM.wsdl" namespace="http://www.example.org/WebServiceATM/">
    </wsdl:import>
  <wsdl:binding name="ATMwsImplServiceSoapBinding" type="ns1:WebServiceATM">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="prelievo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="prelievo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="prelievoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
        <wsdl:operation name="versamento">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="versamento">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="versamentoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ATMwsImplService">
    <wsdl:port binding="tns:ATMwsImplServiceSoapBinding" name="ATMwsImplPort">
      <soap:address location="http://localhost:8080/ATMservice/ATMservice"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>